kind: ConfigMap
apiVersion: v1
metadata:
  name: postgres-config
  labels:
    app: postgres
data:
  POSTGRES_HOST: postgres
  POSTGRES_DB: masajid
  POSTGRES_USER: masajid
---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: postgres-pv-volume
  labels:
    type: local
    app: postgres
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/mnt/data"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: postgres-pv-claim
  labels:
    app: postgres
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:10.4
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5432
          env:
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: postgres
                key: password
          - name: PGDATA
            value: /var/lib/postgresql/data/pgdata
          envFrom:
            - configMapRef:
                name: postgres-config
          volumeMounts:
            - name: postgres-storage
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: postgres-storage
          gcePersistentDisk:
            fsType: ext4
            pdName: postgres-disk
---
kind: Service
apiVersion: v1
metadata:
  name: postgres
  labels:
    app: postgres
spec:
  type: NodePort
  ports:
   - port: 5432
  selector:
   app: postgres
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  labels:
    app: redis
spec:
  selector:
    matchLabels:
      app: redis
  replicas: 1
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
        - name: redis
          image: redis:5.0
          ports:
            - containerPort: 6379
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
          volumeMounts:
            - name: redis-storage
              mountPath: /data
      volumes:
        - name: redis-storage
          gcePersistentDisk:
            fsType: ext4
            pdName: redis-disk
---
apiVersion: v1
kind: Service
metadata:
  name: redis
  labels:
    app: redis
spec:
  type: NodePort
  ports:
    - port: 6379
  selector:
    app: redis
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: masajid-frontend
  labels:
    app: masajid-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: masajid-frontend
  template:
    metadata:
      labels:
        app: masajid-frontend
    spec:
      containers:
      - name: masajid-frontend
        image: eu.gcr.io/masajid-252320/masajid-frontend:1.0.1
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
        env:
        - name: RAILS_SERVE_STATIC_FILES
          value: "true"
        - name: RAILS_MASTER_KEY
          valueFrom:
            secretKeyRef:
              name: rails
              key: master-key
        - name: PROJECT_HOSTNAME
          value: "masajid.world"
        - name: POSTGRES_USER
          valueFrom:
            configMapKeyRef:
              name: postgres-config
              key: POSTGRES_USER
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres
              key: password
        - name: POSTGRES_DATABASE
          valueFrom:
            configMapKeyRef:
              name: postgres-config
              key: POSTGRES_DB
        - name: POSTGRES_HOST
          valueFrom:
            configMapKeyRef:
              name: postgres-config
              key: POSTGRES_HOST
        - name: SUPER_ADMIN_EMAIL
          value: "admin@masajid.world"
        - name: SUPER_ADMIN_PASSWORD
          valueFrom:
            secretKeyRef:
              name: super-admin
              key: password
        - name: ADMIN_SENDER_EMAIL
          value: "admin@masajid.world"
        - name: ADMIN_NOTIFICATION_EMAILS
          value: "admin@masajid.world"
        - name: MAPBOX_ACCESS_TOKEN
          valueFrom:
            secretKeyRef:
              name: mapbox
              key: token
        - name: REDIS_URL
          value: "redis://redis:6379/12"
        - name: GCS_PROJECT_ID
          valueFrom:
            secretKeyRef:
              name: google-cloud-storage-config
              key: gcs-project-id
        - name: GCS_CREDENTIALS
          valueFrom:
            secretKeyRef:
              name: google-cloud-storage-config
              key: gcs-credentials
        - name: GCS_BUCKET_NAME
          valueFrom:
            secretKeyRef:
              name: google-cloud-storage-config
              key: gcs-bucket-name
        envFrom:
        - secretRef:
            name: mailjet
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: masajid-sidekiq
  labels:
    app: masajid-sidekiq
spec:
  replicas: 1
  selector:
    matchLabels:
      app: masajid-sidekiq
  template:
    metadata:
      labels:
        app: masajid-sidekiq
    spec:
      containers:
        - name: masajid-sidekiq
          image: eu.gcr.io/masajid-252320/masajid-frontend:1.0.1
          imagePullPolicy: Always
          command: ["sidekiq", "-C", "config/sidekiq.yml"]
          env:
          - name: RAILS_SERVE_STATIC_FILES
            value: "true"
          - name: RAILS_MASTER_KEY
            value: "7c7b183f59c356cc7277279711d0ace4"
          - name: PROJECT_HOSTNAME
            value: "masajid.world"
          - name: POSTGRES_USER
            valueFrom:
              configMapKeyRef:
                name: postgres-config
                key: POSTGRES_USER
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: postgres
                key: password
          - name: POSTGRES_DATABASE
            valueFrom:
              configMapKeyRef:
                name: postgres-config
                key: POSTGRES_DB
          - name: POSTGRES_HOST
            valueFrom:
              configMapKeyRef:
                name: postgres-config
                key: POSTGRES_HOST
          - name: SUPER_ADMIN_EMAIL
            value: "admin@masajid.world"
          - name: SUPER_ADMIN_PASSWORD
            value: "masajid"
          - name: ADMIN_SENDER_EMAIL
            value: "admin@masajid.world"
          - name: ADMIN_NOTIFICATION_EMAILS
            value: "admin@masajid.world"
          - name: MAILJET_API_KEY
            value: "6b06c311db5162c15ecd15a205ac7664"
          - name: MAILJET_SECRET_KEY
            value: "87e899d768246d46199e55edb0f01016"
          - name: MAPBOX_ACCESS_TOKEN
            value: "pk.eyJ1IjoibWdoYXJiaWsiLCJhIjoiY2pyNWJncTdvMWhuNTQ0cmx3c2xta2hkaiJ9.JJz956L-n8pyAzYBoHDXhw"
          - name: REDIS_URL
            value: "redis://redis:6379/12"
          - name: GCS_PROJECT_ID
            valueFrom:
              secretKeyRef:
                name: google-cloud-storage-config
                key: gcs-project-id
          - name: GCS_CREDENTIALS
            valueFrom:
              secretKeyRef:
                name: google-cloud-storage-config
                key: gcs-credentials
          - name: GCS_BUCKET_NAME
            valueFrom:
              secretKeyRef:
                name: google-cloud-storage-config
                key: gcs-bucket-name
