apiVersion: v1
kind: Service
metadata:
  name: masajid-frontend
  labels:
    app: masajid-frontend
spec:
  externalTrafficPolicy: Cluster
  ports:
  - nodePort: 31647
    port: 80
    protocol: TCP
    targetPort: 3000
  selector:
    app: masajid-frontend
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer: {}
