kind: Deployment
apiVersion: apps/v1
metadata:
  name: masajid-sidekiq
  labels:
    app: masajid-sidekiq
spec:
  replicas: 1
  selector:
    matchLabels:
      app: masajid-sidekiq
  template:
    metadata:
      labels:
        app: masajid-sidekiq
    spec:
      containers:
      - name: masajid-frontend
        image: eu.gcr.io/masajid-252320/masajid-frontend:1.0.1
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
        env:
        - name: RAILS_SERVE_STATIC_FILES
          value: "true"
        - name: RAILS_MASTER_KEY
          valueFrom:
            secretKeyRef:
              name: rails
              key: master-key
        - name: PROJECT_HOSTNAME
          value: "masajid.world"
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres
              key: password
        - name: SUPER_ADMIN_EMAIL
          value: "admin@masajid.world"
        - name: SUPER_ADMIN_PASSWORD
          valueFrom:
            secretKeyRef:
              name: super-admin
              key: password
        - name: ADMIN_SENDER_EMAIL
          value: "admin@masajid.world"
        - name: ADMIN_NOTIFICATION_EMAILS
          value: "admin@masajid.world"
        - name: MAPBOX_ACCESS_TOKEN
          valueFrom:
            secretKeyRef:
              name: mapbox
              key: token
        - name: REDIS_URL
          value: "redis://redis:6379/12"
        envFrom:
        - secretRef:
            name: mailjet
        - secretRef:
            name: google-cloud-storage-config
        - configMapRef:
            name: postgres-config
